config/routes.rb
Rails.application.routes.draw do
  # ゲストログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # ユーザー
  devise_for :users
  root to: "homes#top"

  get "search" => "searches#search" # 検索機能
  get "about"  => "homes#about"
  
  resources :posts, only: [:index, :show, :edit, :create, :update, :destroy, :new] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
      member do
        get :favorites  #いいねされた記事の一覧表示のため
        get :follows, :followers #フォローした人されてる人の一覧表示
      end
      resource :relationships, only: [:create, :destroy] # フォロー機能
  end

  resources :events do
    member do
      get :attendees#参加者一覧
      get :myevent #参加イベント一覧
    end
    resource :attendees, only: [:create, :destroy] #イベントに参加する/参加しない
  end

end

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts                              #記事がなくなるとサイトが成り立たないのでユーザーが消えても記事は残す
  has_many :favorites,    dependent: :destroy  #いいね
  has_many :post_comments                      #コメント ユーザーが消えてもコメントは残す
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy #フォローした
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #フォローされた
  has_many :attendees                          #イベント
  has_many :events,        through: :attendees #イベント
  
  # バリデーション
  validates :name, presence: true
 
 
  #フォロー・フォロワーの一覧を取得
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followeds, source: :follower
 
 
  def follow(user_id) #フォローする時
    followers.create(followed_id: user_id)
  end
 
  def unfollow(user_id) #フォローを外す時
    followers.find_by(followed_id: user_id).destroy
  end
  
  def following?(user) #フォローしてる？
    following_users.include?(user)
  end
 
   def self.looks(search, word) #検索方法
      @user = User.where("title LIKE?","%#{word}%")
   end
 
  has_one_attached :image

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.png')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width,height]).processed
  end
  
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
  # ゲストユーザーログイン
  def guest_user?
    email == GUEST_USER_EMAIL
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :ensure_guest_user, only: [:edit]
 before_action :is_matching_login_user, only: [:edit, :update]

  def index
   @user = current_user
   @posts = @user.posts.page(params[:page]).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.published.page(params[:page]).reverse_order #公開記事のみ表示する(新しい順)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
     if @user.update(user_params)
       flash[:notice] = "Success🎉"
       redirect_to request.referer
     else
       flash.now[:alert] = "Error🫠"
       render 'edit'
     end
  end

  def favorites #いいね一覧表示のための
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: @user.id).pluck(:post_id)
    @favorite_posts = Post.find(favorites)
  end

  def follows #フォローした一覧
    @user = User.find(params[:id])
    @users = @user.following_users
  end

  def followers #フォローされた一覧
    @user = User.find(params[:id])
    @users = @user.follower_users
  end

  def confirm #下書きした記事のみ表示
    @posts = current_user.posts.draft.page(params[:page]).reverse_order
  end

  private
    
       def user_params
        params.require(:user).permit(:name, :introduction, :image, :post_status)
       end
    
       def ensure_guest_user #ゲストユーザーログイン
          @user = User.find(params[:id])
            if @user.guest_user?
              redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
            end
       end
       
       def is_matching_login_user
         user = User.find(params[:id])
            unless user.id == current_user.id
              redirect_to root_path
            end
       end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table">
  <tbody>
      <tr>
        <tr><%= image_tag user.get_image(100,100) %></tr>
      </tr>
      <tr>
        <th>name</th>
        <td><%= link_to user.name, user_path(user) %></td>
      </tr>
      <tr>
        <th>introduction</th>
        <td><%= user.introduction %></td>
      </tr>
      <tr>
        <th>
          <% if user_signed_in? %>
            <% if current_user == user %>
               <!--ユーザー編集ボタン-->
               <%= link_to edit_user_path(current_user.id),class:"btn btn-outline-secondary btn-block" do %>
                  <i class="fas fa-user-cog"></i>
                <% end %>
            <% end %>
          <% end %>
        </th>
      </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container my-5">
  <div class="row justify-content-center ">
    <h3 class="my-3">Profile Setting</h3>
  </div>
  <div class="row">
    <div class="col">
      <%= render 'devise/shared/user-error', user:@user %>
      <%=form_with model: @user, method: :patch do |f|%>
        <table class="table">
          <tr>
            <th>profile image</th>
            <th><%= f.file_field :image, accept: "image/*" %></th>
          </tr>
          <tr>
            <th>name</th>
            <th><%= f.text_field :name, class:"form-control", placeholder:"ここに入力した名前が表示されます" %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= f.text_area :introduction, class:"form-control" %></th>
          </tr>
          <tr>
            <th></th>
            <th><%=f.submit "更新する", class:"btn btn-success" %></th>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
<div>

app/views/users/favorites.html.erb
<div class="container my-5">
  <div class="row my-5 ">
      <div class="col">
        <h3 class >いいねした投稿</h3>
          <% @favorite_posts.each do |post| %>
            <table class="table">
              <tbody>
                <tr>
                  <td><%= link_to post.title, post_path(post) %> </td>
                </tr>
              </tbody>
            </table>
          <% end %>
      </div>
  </div>
</div>

app/views/users/follows.html.erb
<div class="container mt-5">
  <div class="row mt-3">
    <div class="col">
      <h3>フォロー中 <%= @user.followers.count %></h3>
      <% if @users.exists? %>
          <% @users.each do |user| %>
           <table class="table">
             <tbody>
               <tr>
                 <th><%= image_tag user.get_image(100,100) %></th>
                 <th><%= user.name %></th>
              </tr>
             </tbody>
           </table>
          <% end %>
      <% else %>
       <p>フォロー中のユーザーはいません。</p>
      <% end %>
    </div>
    <div class="col">
      <h3>フォロワー <%= @user.followeds.count %></h3>
        <% if @user.follower_users.exists? %>
          <% @user.follower_users.each do |user| %>
             <table class="table">
               <tbody>
                 <tr>
                   <th><%= image_tag user.get_image(100,100) %></th>
                   <th><%= user.name %></th>
                </tr>
               </tbody>
             </table>
          <% end %>
        <% else %>
          <p>フォロワーはいません。</p>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'users' %>
<div class="container my-5">
    <div class="row">
      <div class="col-3">
          <ul>
              <li><%= link_to "フォロー/フォロワー", follows_user_path(@user) %></li>
              <li><%= link_to "Event", myevent_event_path(@user) %></li>
          </ul>
        </div>
        <div class="col m-3">
          <h3 class>記事の管理</h3>
             <table class="table">
              <!--自分の投稿記事一覧-->
                 <tbody>
                  <% @posts.each do |post| %>
                     <tr>
                        <th><%= post.title %></th>
                        <th><%= post.post_status_i18n %></th>
                        <th>
                          <%= link_to edit_post_path(post), class:"btn btn-outline-secondary rounded-circle" do %>
                             <i class="fa-regular fa-pen-to-square"></i>
                          <% end %>
                        </th>
                        <th>
                          <%= link_to post_path(post), method: :delete, class:"btn btn-outline-secondary rounded-circle", data: {confirm: "<確認>削除しますか？"} do %>
                             <i class="fa-solid fa-trash-can"></i>
                          <% end %>
                        </th>
                     </tr>
                  <% end %>
                </tbody>
             </table>
          </div>
      </div>
</div>

app/views/users/myevents.html.erb
<div class="container my-5">
  <div>
    <%= flash[:notice] %>
  </div>
  <h3 class="mb-4">My Event</h3>
  <div class="btn-group mx-2 mb-4">
    <%= link_to "自分が作成したイベント", myevents_user_path(event_type: "created_events"), class: "btn btn-primary" %>
    &nbsp;&nbsp;
    <%= link_to "参加予定イベント", myevents_user_path(event_type: "attended_events"), class: "btn btn-primary" %>
    &nbsp;&nbsp;
    <%= link_to "参加完了イベント", myevents_user_path(event_type: "past_attended_events"), class: "btn btn-primary" %>
  </div>

    <% @myevents.each do |event| %>
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title"><%= link_to event.event_name, event_path(event) %></h5>
          <p class="card-text"><strong>開催日：</strong><%= event.date %></p>
          <p class="card-text"><strong>参加URL : </strong><%= link_to  event.url %></p>
        </div>
      </div>
    <% end %>
 

app/views/users/show.html.erb
<div class="container my-5">
 <!--今ログインしているユーザーのプロフィール-->
 <div class="row">
    <div class="col-3">
     <%= image_tag @user.get_image(150,150),class:'profile-image' %>
    </div>
    <div class="col-8">
      <table class="table">
        <tbody>
         <tr>
          <th><%= @user.name %></th>
         </tr>
         <tr>
          <td><%= @user.introduction %></td>
         </tr>
        </tbody>
       </table>
    </div>
    <div class="col-2">
      <!--ユーザー編集ボタン-->
      <% if user_signed_in? %>
       <% unless @user.guest_user? %> <!--ゲストユーザーであるかどうか-->
          <% if current_user == @user %> <!--現在ログイン中のユーザーかどうか-->
                 <%= link_to "Edit plofile", edit_user_path(current_user.id),class:"btn btn-outline-secondary btn-block" %>
           <% end %>
       <% end %>
        <div id="follow_<%= @user.id %>">
              <%= render 'relationships/follow_btn', user: @user %><!--フォローボタン-->
        </div>
       <% end %>
    </div>
 </div>
 <div class="row my-5">
    <div class="col-9">
     <h3>My Page</h3>
    </div>
    <div class="col-3 justify-content-end">
     <% if user_signed_in? %>
       <!--新しい記事を書くボタン-->
         <%= link_to new_post_path, class:"btn  btn-outline-secondary" do %>
             新しい記事を書く<i class="fa-solid fa-pencil"></i>
         <% end %>
      <% end %>
    </div>
 </div>
 
   <div class="row">
    <% @posts.each do |post| %>
      <div class="col.justify-content-around m-3">
         <!--投稿一覧-->
             <div class="card shadow" style="width: 20rem;">
               <a href="/posts/<%= post.id %>" class="text-dark">
                 <%= image_tag post.get_post_image(320,400), class:"card-img-top"  %>
                   <h5 class="card-title"><strong><%= post.title %></strong></h5>
                   <h6 class="card-text2"><%= post.body %></h6>
                   <i class="fa-regular fa-heart"> <%= post.favorites.count %></i>
                   <i class="fa-regular fa-comment"> <%= post.post_comments.count %></i>
                </a>
             </div>
      </div>
    <% end %>
   </div>
</div>