config/routes.rb
Rails.application.routes.draw do
  # ゲストログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # ユーザー
  devise_for :users
  root to: "homes#top"

  get "search" => "searches#search" # 検索機能
  get "about"  => "homes#about"
  
  resources :posts, only: [:index, :show, :edit, :create, :update, :destroy, :new] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
      member do
        get :favorites  #いいねされた記事の一覧表示のため
        get :follows, :followers #フォローした人されてる人の一覧表示
      end
      resource :relationships, only: [:create, :destroy] # フォロー機能
  end

  resources :events do
    member do
      get :attendees#参加者一覧
      get :myevent #参加イベント一覧
    end
    resource :attendees, only: [:create, :destroy] #イベントに参加する/参加しない
  end

end

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendees
  belongs_to :creator, class_name: "User"
  has_many :users, through: :attendees

  scope :latest, -> {order(created_at: :desc)} #新しい順に並べる
  
  enum event_status: { offline: 0, online: 1 } #イベント開催オフラインかオンラインか
  
  
  
  # バリデーション
  validates :event_name, :date, :event_introduction, presence: true

  def includesUSesr?(user) #ユーザーがイベントの参加者かどうか
    attendees.exists?(attendee_id: user_id)
  end
  

  validate :date
   def date_check #dateが今日より前の日付は設定できないようにする。
     unless date == nill
       errors.add(:date,"は今日以降の日付を入力してください")if date < Date.tody
     end
   end

  has_one_attached :event_image

  def get_event_image(width,height)
    unless event_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.png')
      event_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      event_image.variant(resize_to_limit: [width,height]).processed
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]
  
  def new
    @event = Event.new
  end
  
  def create
    @event = Event.new(event_params)
    @event.creator = current_user
    if @event.save
       flash[:notice] = "Success🎉"
       redirect_to event_path(@event)
    else
      flash.now[:alert] = "Error🫠"
      render "new"
    end
  end
  
  def edit
    @event.creator = ensure_correct_user
    @event = Event.find(params[:id])
  end
  
  def update
    @event = Event.find(params[:id])
    @event.creator = current_user
    if @event.update(event_params)
      flash[:notice] = "Success🎉"
      redirect_to event_path(@event)
    else
      flash.now[:alert] = "Error🫠"
      render "edit"
    end
  end
  
  def destroy
    @event = Event.find(params[:id])
    @event.destroy!
    redirect_to events_path
  end
  
  def index
    @events = Event.latest
  end
  
  def show
    @event = Event.find(params[:id])
    @user = @event.creator
    if user_signed_in?
      @attendee = Attendee.find_by(user_id: current_user.id, event_id: @event.id)
    end
  end
  
  def myevent
    @events = Event.all
    
    if params[:event_type] == "created_events"
      @myevents = @events.where(creator_id: current_user.id)
    elsif params[:event_type] == "attended_events"
      @myevents = Event.joins(:attendees).where(attendees: { user_id: current_user.id }).where.not(creator_id: current_user.id).page(params[:page]).per(8)
    elsif params[:event_type] == "past_attended_events"
      @myevents = Event.joins(:attendees).where(attendees: { user_id: current_user.id }).where("date < ?", Time.now).where.not(creator_id: current_user.id).page(params[:page]).per(8)
    else
      @myevents = Event.joins(:attendees).where(attendees: { user_id: current_user.id }).page(params[:page]).per(8)
    end
  end
  
  
  private
  
  def event_params
    params.require(:event).permit(:event_image, :event_name, :event_introduction, :date, :url, :postal_code, :adress)
  end
  
   def ensure_correct_user
    @event = Event.find(params[:id])
    unless @event.creator == current_user
      redirect_to root_path
    end
   end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
 <div class="row m-5">
   <% events.each do |event| %>
      <div class="col.justify-content-around m-3">
          <div class="card event-card" style="width: 18rem;">
            <a href="/events/<%= event.id %>" class="card text-dark">
                開催日<%= event.date.strftime('%Y/%m/%d') %>
                <%= image_tag event.get_event_image(400,400),class:"card-img-top" %>
                <h4 class="card-title"><%= event.event_name %></h4>
            </a>
          </div>
      </div>
    <% end %>
 </div>

app/views/events/_image.html.erb
<script>
  function avatarImage(obj){
      var fileReader = new FileReader();
      fileReader.onload = (function() {
        document.getElementById('avatar_preview').src = fileReader.result;
      });
      fileReader.readAsDataURL(obj.files[0]);
  }
</script>

app/views/events/edit.html.erb
<div class="container my-5">
  <h3 class>Edit Event</h3>
   <div class="row">
     <div class="col-6">
        <div id="event_images" style="display: none;">
          <p id="preview"></p>
        </div>
     </div>
     <div class="col-6">
        <%= render 'devise/shared/event-error', event:@event %>
        <%= form_with model:@event, url: event_path(@event) do |f| %>
          <table class="table table-borderless">
            <tbody>
              <tr><th>
                <%= f.datetime_field :date, class: "form-control" %>
              </th></tr>
              <tr><th>
                <label class>
                <i class="fa-regular fa-image"></i>
                <%= f.file_field :event_image, accept: "image/*", onchange: "avatarImage(this);"%>
                </label>
              </th></tr>
              <tr><td><%= f.text_field :event_name, placeholder:"イベントタイトル", class:'form-control' %></td></tr>
              <tr><td><%= f.text_area :event_introduction,rows:"15", placeholder:"イベント詳細", class:'form-control' %></td></tr>
              <tr>
                <td>
                
                <%= f.radio_button :event_status, :offline %><%= f.label :"オフライン"%>
                <%= f.radio_button :event_status, :online %><%= f.label :"オンライン" %>
                </td>
              </tr>
              <tr><td><%= f.text_area :url, placeholder:"オンライン開催URL", class:'form-control' %></td></tr>
              <tr><td><%= f.text_field :postal_code, placeholder:"〒 郵便番号", class:'form-control' %></td></tr>
              <tr><td><%= f.text_area :adress,rows:"4", placeholder:"住所", class:'form-control'%></td> </tr>
              <tr><td><%= f.submit "更新する", class: "btn btn-success" %></td></tr>
            </tbody>
          </table>
        <% end %>
      </div>
  </div>
</div>

app/views/events/index.html.erb
<%= stylesheet_link_tag 'events' %>
<div class="container my-5">
  <div class="row my-5">
    <div class="col">
      <h3 class>イベント一覧</h3>
      <% if user_signed_in? %>
        <%= link_to "新しいイベントを作成する", new_event_path, class:"btn btn-outline-secondary" %>
      <% end %>
    </div>
  </div>
  <%= render 'event',  events: @events %>
</div>

app/views/events/myevent.html.erb
<%= stylesheet_link_tag 'events' %>
<div class="container my-5">
  <h3 class="mb-4">My Event</h3>
  <div class="btn-group mx-2 mb-4">
    <%= link_to "自分が作成したイベント", myevent_event_path(event_type: "created_events"), class: "btn btn-primary" %>
    &nbsp;&nbsp;
    <%= link_to "参加予定イベント", myevent_event_path(event_type: "attended_events"), class: "btn btn-primary" %>
    &nbsp;&nbsp;
    <%= link_to "参加完了イベント", myevent_event_path(event_type: "past_attended_events"), class: "btn btn-primary" %>
  </div>
  <div class="row m-5">
   <% @myevents.each do |event| %>
      <div class="col.justify-content-around m-3">
          <div class="card" style="width: 18rem;">
             <a href="/events/<%= event.id %>" class="card text-dark">
                更新日<%= event.created_at.strftime('%Y/%m/%d') %>
                <%= image_tag event.get_event_image(400,400),class:"card-img-top" %>
                <h4 class="card-title"><%= event.event_name %></h4>
                <p class="card-text"><%= event.event_introduction %></p>
             </a>
          </div>
      </div>
   <% end %>
 </div>
</div>

app/views/events/new.html.erb
<div class="container my-5">
  <h3 class="my-3">New Event</h3>
   <div class="row">
     <div class="col-6">
        <div id="event_images" style="display: none;">
          <p id="preview"></p>
        </div>
     </div>
     <div class="col-6">
       <%= render 'devise/shared/event-error', event:@event %>
        <%= form_with model:@event, url:events_path do |f| %>
          <table class="table table-borderless">
            <tbody>
              <tr><th>
                <%= f.datetime_field :date %>
              </th></tr>
              <tr><th>
                <label class>
                <i class="fa-regular fa-image"></i>
                <%= f.file_field :event_image, accept: "image/*", onchange: "avatarImage(this);"%>
                </label>
              </th></tr>
              <tr><td><%= f.text_field :event_name, placeholder:"イベントタイトル", class:'form-control' %></td></tr>
              <tr><td><%= f.text_area :event_introduction,rows:"15", placeholder:"イベント詳細", class:'form-control' %></td></tr>
              <tr>
                <td>
                
                <%= f.radio_button :event_status, :offline %><%= f.label :"オフライン"%>
                <%= f.radio_button :event_status, :online %><%= f.label :"オンライン" %>
                </td>
              </tr>
              <tr><td><%= f.text_area :url, placeholder:"オンライン開催URL", class:'form-control' %></td></tr>
              <tr><td><%= f.text_field :postal_code, placeholder:"〒 郵便番号", class:'form-control' %></td></tr>
              <tr><td><%= f.text_area :adress,rows:"4", placeholder:"住所", class:'form-control'%></td> </tr>
              <tr><td><%= f.submit "作成する", class: "btn btn-success" %></td></tr>
            </tbody>
          </table>
        <% end %>
      </div>
  </div>
</div>

app/views/events/radio_btn.js.erb
const select = document.querySelector("#select")
select.addEventListener("change", () => {
  const b = document.querySelector(".b")
  if (select.value === "B") {
    b.style.visibility = "visible"
  } else {
    b.style.visibility = "hidden"  
  }
})

app/views/events/show.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col event-image">
      <%= image_tag @event.get_event_image(700,700) %>
    </div>
  </div>
  <div class="row">
     <table class="table table-borderless">
       <tbody>
           <tr>
           <td><p id="title"><%= @event.event_name %></p></td>
           </tr>
           <tr>
             <td><p class="item">1.詳細</p></td>
           </tr>
           <tr>
             <td><%= @event.event_introduction %></td>
           </tr>
           <tr>
             <td><p class="item">2. 開催形態</p></td>
           </tr>
           <tr>
             <td><%= @event.event_status %></td>
           </tr>
           <tr>
             <td><p class="item">3. 開催日時</p></td>
           </tr>
           <tr>
             <td><%= @event.date.strftime('%Y/%m/%d/%H時～') %></td>
           </tr>
           <tr>
             <td><p class="item">4. 開催場所</p></td>
           </tr>
           <tr>
             <td>
               <%= @event.url %><br>
               <%= @event.postal_code %><br>
               <%= @event.adress %>
             </td>
           </tr>
           <tr>
             <td><p class="item">5. 作成者</p></td>
           </tr>
           <tr>
             <td><%= link_to @event.creator.name, user_path(@user)%></td>
           </tr>

       </tbody>
     </table>
  </div>
          <div class="row">
               <!--イベントの編集　イベント作成者の場合-->
              <% if user_signed_in? %>
               <% if current_user == @event.creator %>
                  <%= link_to edit_event_path(@event), class:"btn btn-success" do %>
                       編集
                  <% end %>
                  <%= link_to event_path(@event), class:"btn btn-danger", method: :delete, data: {confirm: "<確認>削除しますか？"} do %>
                       削除
                  <% end %>
                <% end %>
              <% end %>

               <!--イベント参加の有無　イベント作成者ではないひとがログインしている場合-->
               <% if user_signed_in? %>
                    <% if @event.creator.id != current_user.id %>
                        <% if @attendee %>
                            <%= button_to '参加済み', event_attendees_path(@event, @attendee), disabled: true, class: 'btn btn-secondary mr-3' %>
                            <%= link_to "参加取り消し", event_attendees_path(@event, @attendee), class:'btn btn-sm btn-danger', method: :delete, data: { confirm: '本当に変更しますか？' } %>
                         <% else %>
                             <%= button_to '参加する', event_attendees_path(@event), class: 'btn btn-primary mr-3' %>
                          <% end %>
                     <% end %>
              <% else %>
                     <%= link_to '会員登録して参加する', new_user_registration_path, class: 'btn btn-primary mr-3' %>
              <% end %>
          </div>
          <div class="row">
            <!--参加者-->
            <% if current_user == @event.creator %>
                <% @event.users.each do |user| %>
                   <table class="table">
                       <thead>
                           <th>Member list</th>
                       </thead>
                       <tbody>
                           <tr>
                             <td><%= user.name %></td>
                             <td><%= user.email %></td>
                           </tr>
                       </tbody>
                   </table>
                <% end %>
            <% end %>
          </div>
</div>