config/routes.rb
Rails.application.routes.draw do
  # ゲストログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # ユーザー
  devise_for :users
  root to: "homes#top"

  get "search" => "searches#search" # 検索機能
  get "about"  => "homes#about"
  
  resources :posts, only: [:index, :show, :edit, :create, :update, :destroy, :new] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
      member do
        get :favorites  #いいねされた記事の一覧表示のため
        get :follows, :followers #フォローした人されてる人の一覧表示
      end
      resource :relationships, only: [:create, :destroy] # フォロー機能
  end

  resources :events do
    member do
      get :attendees#参加者一覧
      get :myevent #参加イベント一覧
    end
    resource :attendees, only: [:create, :destroy] #イベントに参加する/参加しない
  end

end

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  scope :latest, -> {order(created_at: :desc)} #postを新着順に表示できるようにする
  scope :impressions_count, -> {order(impressions_count: :desc)} #postをpvの多い順に表示できるようにする

  enum post_status: { draft: 0, published: 1 } #下書き,投稿のenumステータス

  has_many :favorites,                   dependent: :destroy #いいね機能
  has_many :post_comments,               dependent: :destroy #コメント機能
  has_many :post_tag_relationships,      dependent: :destroy #タグ機能
  has_many :post_tags,                   through: :post_tag_relationships

  is_impressionable counter_cache: true #PV数計測

  # バリデーション
  validates :title, :body, :post_status, presence: true
 
 #検索
  def self.search_content(content, method)
    if method == "perfect"
      where(title: content)
    elsif method == "partial"
      where("title LIKE ?", "%#{content}%")
    else
      all
    end
  end

  def save_post_tags(tags) #タグ追加する
    current_tags = self.post_tags.pluck(:name) unless self.post_tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags

    # 古いタグを消す
    old_tags.each do |old_name|
      self.post_tags.delete PostTag.find_by(name:old_name)
    end

    # 新しいタグを保存
    new_tags.each do |new_name|
      post_tag = PostTag.find_or_create_by(name:new_name)
      self.post_tags << post_tag
    end
  end


  def update_post_tags(latest_post_tags) #タグの更新

    if self.post_tags.empty?        #既に登録していたタグが消去されていたら追加のみ行う
        latest_post_tags.each do |latest_post_tag|
          self.post_tags.find_or_sreate_by(name: latest_tag)
        end
    elsif latest_post_tags.empty?  #更新するタグがなかったら既存のタグをすべて消去
      self.post_tags.each do |post_tag|
        self.post_tags.delete(post_tag)
      end
    else
      current_post_tags = self.post_tags.pluck(:name)
      old_post_tags = current_post_tags - latest_post_tags
      new_post_tags = latest_post_tags - current_post_tags

      old_post_tags.each do |old_post_tag|
        post_tag = self.post_tags.find_by(name: old_post_tag)
        self.post_tags.delete(post_tag) if post_tag.present?
      end

      new_post_tags.each do |new_post_tag|
        self.post_tags.find_or_create_by(name: new_post_tag)
      end
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  has_one_attached :post_image #投稿の画像表示

  def get_post_image(width, height)
    unless post_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.png')
      post_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      post_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :ensure_correct_user, only: [:edit, :update]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    post_tags = params[:post][:name].split(',')
    if  @post.save
        @post.save_post_tags(post_tags)
        flash[:notice] = "Success🎉"
        redirect_to users_path
    else
        flash.now[:alert] = "Error🫠"
        render :new  #保存に失敗したらnewページに戻る
    end
  end

  def index
    @posts = Post.published.page(params[:page]).reverse_order #公開記事のみ表示
  end

   impressionist :actions=> [:show] #showページを開いたらPV数を計測

  def show
     @post = Post.find(params[:id])
     @user = @post.user
     @post_comment = PostComment.new
     @post_tags = @post.post_tag_relationships #タグ表示
     impressionist(@post, nil, unique: [:session_hash]) #pv数計測

  end

  def edit
    @post = Post.find(params[:id])
    @post_tags = @post.post_tags.pluck(:name).join(',')  #タグの編集
  end

  def update
     @post = Post.find(params[:id])
     tag_list = params[:post][:name].split(',')
     if@post.update(post_params)
       @post.save_post_tags(tag_list)
       flash[:notice] = "Success🎉"
       redirect_to post_path(@post)
     else
       flash.now[:alert] = "Error🫠"
       render :edit
     end
  end

  def destroy #記事の削除
     post = Post.find(params[:id])
     post.destroy
     flash[:notice] = "Success🎉"
     redirect_to users_path
  end



  private

  def post_params
    params.require(:post).permit(:title, :body, :post_status, :post_image)
  end

  def ensure_correct_user
    @post = Post.find(params[:id])
    unless @post.user == current_user
      redirect_to root_path
    end
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_search.html.erb
<div class="form-inline">
      <%= form_with url: search_path, method: :get do |f| %>
          <%= f.text_field :content, placeholder:"キーワードを入力", class:'rounded-pill form-control' %>
          <%= f.select :model, options_for_select({"Post" => "post"}) %>
          <%= f.select :method,options_for_select({"完全一致"=>"perfect","部分一致"=>"partial"})%>
          <%= button_tag type: "submit", class:'btn btn-outline-success' do %>
            <i class="fa-solid fa-magnifying-glass"></i>
          <% end %>
      <% end %>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <h3 class="my-5"> Post Edit</h3>
     <div class="row">
      <div class="col-12">
        <%= render 'devise/shared/post-error', post: @post %>
        <%= form_with model: @post, url:post_path(@post), method: :patch do |f| %>
            <table class="table table-borderless">
              <tbody>
                     <tr> <!--タグ登録-->
                        <td> <%= f.text_field :name,value: @tag_list, placeholder:"タグ(,で区切ると複数タグ登録できます)", class:'form-control' %></td>
                     </tr>
                     <tr> <!--タイトルフォーム-->
                        <td><%= f.text_field :title, placeholder:"タイトル", class:'form-control' %></td>
                     </tr>
                     <tr> <!--本文フォーム-->
                        <td><%= f.text_area :body,rows:"15", placeholder:"本文", class:'form-control' %></td>
                     </tr>
                     <tr> <!--サムネ画像投稿-->
                        <td><%= f.file_field :post_image, accept:"image/*" %></td>
                     </tr>
                     <tr> <!--ステータス選択-->
                        <td><%= f.select :post_status, Post.post_statuses.keys.map{ |k| [t("enums.post.post_status.#{k}"),k]}, {}, {class:"custom-select w-25"} %></td>
                     </tr>
                     <tr> <!--保存ボタン、削除ボタン-->
                        <td>
                        <%= f.submit "更新する", class: "btn btn-success" %>
                           <%= link_to post_path(@post), method: :delete, class:"btn btn-danger", data: {confirm: "<確認>削除しますか？"} do %>
                              記事を削除する<i class="fa-solid fa-trash-can"></i>
                           <% end %>
                        </td>
                    </tr>
              </tbody>
          </table>
       <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container mt-7 my-3">
  <div class="row-1 m-5">
      <!--検索欄-->
      <%= render 'search' %>
  </div>
     <div class="row">
       <div class="col">
         <table class="table">
          <!--みんなの投稿記事一覧-->
           <tbody>
            <% @posts.each do |post| %>
               <tr>
                <td><%= image_tag post.get_post_image(50,50)%></td>
                <th><%= link_to post.title,post_path(post) %></th>
                <td><i class="fa-regular fa-face-kiss-wink-heart"></i><%= post.favorites.count %></td>
                <td><i class="fa-regular fa-comment"></i><%= post.post_comments.count %></td>
                <td><i class="fa-regular fa-eye"></i><%= post.impressions_count  %></td>
                <td><%= post.created_at.strftime('%Y/%m/%d') %></td>
               </tr>
            <% end %>
          </tbody>
         </table>
       </div>
  </div>
</div>

app/views/posts/new.html.erb
   <div class="container my-5">
     <h3 class="my-5">New Post</h3>
       <div class="row">
         <div class="col-12">
           <%= render 'devise/shared/post-error', post: @post %>
           <%= form_with model:@post, url:posts_path do |f| %>
             <table class="table table-borderless">
                <tbody>
                   <tr>
                      <td> <%= f.text_field :name,value: @tag_list, placeholder:"タグ(,で区切ると複数タグ登録できます)", class:'form-control' %></td>
                  </tr>
                   <tr>
                      <td><%= f.text_field :title, placeholder:"タイトル", class:'form-control' %></td>
                   </tr>
                   <tr>
                      <td><%= f.text_area :body,rows:"15", placeholder:"本文", class:'form-control' %></td>
                   </tr>
                   <tr>
                      <td><%= f.file_field :post_image, accept: "image/*" %></td>
                  </tr>
                  <tr>
                      <td> <%= f.select :post_status, Post.post_statuses.keys.map{ |k| [t("enums.post.post_status.#{k}"),k]}, {}, {class: "custom-select w-25"} %></td>
                  </tr>
                  <tr>
                      <td> <%= f.submit "保存する", class: "btn btn-success" %>
                  </td>
                  </tr>
                </tbody>
              </table>
           <% end %>
         </div>
       </div>
   </div>

app/views/posts/show.html.erb
<div class="container my-5">
  <div class="row">
      <div class="col">
        <% if user_signed_in? %>
            <!--My pageに戻るボタン-->
            <%= link_to user_path(current_user),class:"btn btn-outline-secondary rounded-circle my-4" do %>
             <i class="fa-solid fa-angles-left"></i>
            <% end %><br>
            <!--非同期化-->
            <div id="favorite_buttons_<%= @post.id %>">
              <!--お気に入りボタン-->
              <%= render'favorites/favorite-btn', post: @post %>
            </div>
        <% end %>
      </div>
      <!--記事の詳細-->
      <div class="col-8">
        <div class="post_image"><%= image_tag @post.get_post_image(250,250) %></div>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td>
                 <% @post_tags.each do |tag| %>
                    <i class="fa-solid fa-hashtag"></i><%= tag.post_tag.name %>
                 <% end %>
              </td>
            </tr>
            <tr>
              <td><h3><%= @post.title %></h3></td>
            </tr>
            <tr>
              <td><%= @post.body %></td>
            </tr>
            <tr>
              <td>投稿日<%= @post.created_at.strftime('%Y/%m/%d') %></td>
            </tr>
          </tbody>
        </table>
       </div>
       <div class="col-3">
        <% if current_user == @post.user %>
        <!--記事の編集-->
          <%= link_to edit_post_path(@post), class:"btn btn-outline-secondary" do %>
               記事の編集
          <% end %>
        <% end %>
          <div class="row m-3">
          <!--この記事を書いたUserプロフィール-->
          <%= render 'users/index', user: @user %>
          <% if user_signed_in? %>
            <div id="follow_<%= @user.id %>">
               <%= render 'relationships/follow_btn', user: @user %><!--フォローボタン-->
            </div>
          <% end %>
          </div>
       </div>
    </div>
       <div class="row mx-5">
        <div class="col">
           <!--コメント欄-->
          <div id="post_comments">
              <%= render 'post_comments/index', post: @post, post_comments: @post_comments %><!--コメント一覧-->
          </div>
          <% if user_signed_in? %>
            <div id="comment_form">
                <%= render 'post_comments/form', post: @post, post_comment: @post_comment %><!--コメント入力フォーム-->
            </div>
          <% end %>
        </div>
       </div>
  </div>
 