config/routes.rb
Rails.application.routes.draw do
  # ゲストログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # ユーザー
  devise_for :users
  root to: "homes#top"

  get "search" => "searches#search" # 検索機能
  get "about"  => "homes#about"
  
  resources :posts, only: [:index, :show, :edit, :create, :update, :destroy, :new] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
      member do
        get :favorites  #いいねされた記事の一覧表示のため
        get :follows, :followers #フォローした人されてる人の一覧表示
      end
      resource :relationships, only: [:create, :destroy] # フォロー機能
  end

  resources :events do
    member do
      get :attendees#参加者一覧
      get :myevent #参加イベント一覧
    end
    resource :attendees, only: [:create, :destroy] #イベントに参加する/参加しない
  end

end

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job</title>
    <%= favicon_link_tag('favicon.ico') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/9e6c78803c.js" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application' %>
  </head>
  <body>
      <header>
         <nav class="navbar navbar-expand-lg m-5">
             <%= render 'devise/shared/humberger' %>
               <a class="navbar-brand mx-auto" href="/"><%= image_tag asset_path('JOB-logos.jpg'), class:"logo" %></a>
                 <ul class="navbar-nav">
                  <% if user_signed_in? %>
                      <li class="nav-item mr-3">
                        <%= link_to posts_path do %>
                            <i class="fa-solid fa-magnifying-glass"></i><!--検索-->
                        <% end %>
                      </li>
                   <% else %>
                      <li class="nav-item mr-1">
                        <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, class: "btn", method: :post %>
                      </li>
                      <li class="nav-item mr-1">
                        <%= link_to "新規登録", new_user_registration_path, class:"btn" %>
                      </li>
                       <li class="nav-item mr-1">
                         <%= link_to posts_path, class:"btn" do %>
                        <i class="fa-solid fa-magnifying-glass"></i><!--検索-->
                        <% end %>
                      </li>
                  <% end %>
                 </ul>
              </nav>
          </div>
      </header>
       <main>
          <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
          <% flash.each do |message_type, message| %>
              <div class="flash-message <%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
       </main>
       <footer>
          <ul class="footer-item">
             <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa-solid fa-right-from-bracket"></i>ログアウトする方はこちら
            　<% end %>
          </ul>
          <p class="footer-item">© NANIWOSUREBAIINOKA TADASIISENNTAKUTOHA</p>
      </footer>
  </body>
</html>